USE PRACTICA1;
DROP TABLE IF EXISTS Temporal;
DROP TABLE IF EXISTS Passenger;
DROP TABLE IF EXISTS Airport;
DROP TABLE IF EXISTS Flight;
DROP TABLE IF EXISTS Pilot;
DROP TABLE IF EXISTS Nationality;
DROP TABLE IF EXISTS Continent;
DROP TABLE IF EXISTS Timeline;
DROP TABLE IF EXISTS Flight_Details;

-- DROP DATABASE PRUEBA;