version: '3.8'

services:
  db:
    build: .
    container_name: db-prueba
    environment:
      SA_PASSWORD: "SuperSmash123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/data
